[package]
name = "sound-daemon"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sound-daemon"
test = false
bench = false
path = "src/sound-daemon/bin/main.rs"

[dependencies.syscall-defs]
path = "../../syscall-defs"

[dependencies.syscall-user]
path = "../syscall-user"
